-- Run with CockroachDB's SQL client using an administrative migration account:
-- cockroach sql --url '<admin connection URL selecting database sky_event>' \
--   --set=errexit=true \
--   --file=Migrations/20260728121000_PurchaseConfirmationDeliveryOutbox.cockroach.sql
--
-- CockroachDB DDL is intentionally not wrapped in a transaction. The history
-- row is inserted last, after the table, indexes, and application grants exist.

SELECT current_database() AS migration_database, current_user AS migration_user;

-- Stop if this connection points at the wrong database.
SELECT 1 / CASE WHEN current_database() = 'sky_event' THEN 1 ELSE 0 END
    AS correct_database;

-- Stop if the application principal does not exist.
SELECT 1 / CASE WHEN count(*) = 1 THEN 1 ELSE 0 END
    AS sky_event_user_exists
FROM [SHOW USERS]
WHERE username = 'sky_event';

-- This migration must follow the existing EventBroker migration chain.
SELECT 1 / CASE WHEN count(*) = 1 THEN 1 ELSE 0 END
    AS predecessor_applied
FROM public."__EFMigrationsHistory"
WHERE "MigrationId" = '20240228201753_SeparateSubId';

-- Refuse a replay or a partially/manual-created target table.
SELECT 1 / CASE WHEN count(*) = 0 THEN 1 ELSE 0 END
    AS migration_unapplied
FROM public."__EFMigrationsHistory"
WHERE "MigrationId" = '20260728121000_PurchaseConfirmationDeliveryOutbox';

SELECT 1 / CASE WHEN count(*) = 0 THEN 1 ELSE 0 END
    AS target_table_absent
FROM information_schema.tables
WHERE table_catalog = current_database()
  AND table_schema = 'public'
  AND table_name = 'PurchaseConfirmationDeliveries';

CREATE TABLE public."PurchaseConfirmationDeliveries" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Reference" character varying(32) NOT NULL,
    "Recipient" character varying(320),
    "Locale" character varying(16),
    "Payload" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "NextAttemptAt" timestamp with time zone NOT NULL,
    "SentAt" timestamp with time zone,
    "FailedAt" timestamp with time zone,
    "Attempts" integer NOT NULL,
    "LeaseId" uuid,
    "LeaseUntil" timestamp with time zone,
    "LastError" character varying(2000),
    CONSTRAINT "PK_PurchaseConfirmationDeliveries" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_PurchaseConfirmationDeliveries_Reference"
ON public."PurchaseConfirmationDeliveries" ("Reference");

CREATE INDEX "IX_PurchaseConfirmationDeliveries_SentAt_FailedAt_NextAttemptAt"
ON public."PurchaseConfirmationDeliveries" ("SentAt", "FailedAt", "NextAttemptAt");

-- The application already connects to sky_event, but make its database/schema
-- access and least-privilege access to the new objects explicit.
GRANT CONNECT ON DATABASE sky_event TO sky_event;
GRANT USAGE ON SCHEMA public TO sky_event;
GRANT SELECT, INSERT, UPDATE
ON TABLE public."PurchaseConfirmationDeliveries"
TO sky_event;
GRANT USAGE
ON SEQUENCE public."PurchaseConfirmationDeliveries_Id_seq"
TO sky_event;

INSERT INTO public."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260728121000_PurchaseConfirmationDeliveryOutbox', '10.0.10');

-- Post-migration evidence.
SELECT "MigrationId", "ProductVersion"
FROM public."__EFMigrationsHistory"
WHERE "MigrationId" = '20260728121000_PurchaseConfirmationDeliveryOutbox';

SHOW CREATE TABLE public."PurchaseConfirmationDeliveries";
SHOW INDEXES FROM public."PurchaseConfirmationDeliveries";
SHOW GRANTS ON TABLE public."PurchaseConfirmationDeliveries" FOR sky_event;
SHOW GRANTS FOR sky_event;
